= LAYER 2 SEGMENT IN XXX dc
:doctype: book 
:preface-title: Preface 
:toc:

== Preface
This is preface
== Chapter A
== Chapter B


== Overview

This document describe the `solution building block` of the `Layer 2 segment` in XX data center

== Supported DCs

* DC1
* DC2
* DC3
* DC4
* DC5

== Description

Endpoints connected to the Layer 2 segment can communicate freely without any network restriction when they are the same IP subnet. On the other hand, the Layer2 segment prevent any connectivity to endpoints outside the segment.


== Use Cases

ISCSI Connectivity:: ISCSI require Layer 2 network to operate, this is to # <1> Limit the external access. # <2> Improve performance
HeartBeat (HA) network:: Similar to the ISCSI use case, HA require typically a layer 2 network between the systems
General Layer2 connecivity:: any system require an isolated network boundry and leverage the Layer 2 segment.

== Architectural Diagram

== Limitations and considerations
Performance:: it is advised that not more than 512 endpoint connect to a single Layer 2 segment.
Supported Segments:: maximum of 1000 Layer 2 segment can be created per datacenter, https://monitoring/epg[here] you can refer to the current utalization
== How to request the product
You can use https://xxx/Req999[REQ999] to request this product

== Monitoring And Obervability


== Troubleshooting
[source, python]

----
Interface X # <1>
 switchport trunk allowed vlan Y # <2>
----

<1> The interface where the allowed VLANs would be set on
<2> The specific VLANs to add


